name: obs-validation-dev
channels:
    - conda-forge
    - nodefaults
    - pyviz
dependencies:
    - bokeh
    - bottleneck
    - distributed
    - dask
    - ncar-jobqueue
    - xarray
    - pyyaml
    - intake-esm
    - holoviews
    - geoviews
    - hvplot
    - datashader
    - panel
    - matplotlib
    - jupyterlab
    - xesmf
    - pop-tools
    - pip
    - pip:
      - ecgtools
